### ISSUE TITLE
Error when invoking without -ignoretagsregex

### ISSUE THREAD

**Issue by rchekaluk** [awslabs/ecr-cleanup-lambda#26]
```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    os.environ["IGNORE_TAGS_REGEX"] = args.ignoretagsregex
  File "/usr/lib64/python2.7/os.py", line 471, in __setitem__
    putenv(key, item)
TypeError: must be string, not None
```

Workaround:
```
$ python main.py -ignoretagsregex dummy
```

**Comment by hposca** [comment]
This was solved on #27 apparently

**Comment by archetypalsxe** [comment]
Confirmed that this is no longer occurring
